#!/bin/bash
#Requrements:
#1. imagemagick
#2. exiv2
#3. coreutils

source "$(dirname "$0")/env"

exec 2>>${LOG_FILE}

control_size $LOG_FILE $MAX_LOG_SIZE

s=" :: "

filename=$(_cut "$(basename "$1")" 60)
filesize=$(du -Hh "$1" | cut -f 1) 
geometry=$(identify -format '%wx%h' "$1[0]")

tags=$(exiv2 -q pr "$1" 2>/dev/null | awk '$1~"Keywords" { printf("%s,", $4); }')
tags=${tags%,}

dstdir=$(tail -n1 $dstf)
[[ $? != 0 ]] && dstdir="N/A"

echo "${filesize}${s}${geometry}${tags:+$s}${tags}${s}${filename}${s}${dstdir}"
