#!/bin/sh
source "$(dirname "$0")/env"

s=" :: "

filename=$(_cut "$(basename "$1")" 60)
filesize=$(du -Hh "$1" | cut -f 1) 
geometry=$(identify -format '%wx%h' "$1[0]")

tags=$(exiv2 -q pr "$1" 2>/dev/null | awk '$1~"Keywords" { printf("%s,", $4); }')
tags=${tags%,}

dstdir="$(head $dstf 2>/dev/null || echo N/A)"

echo "${filesize}${s}${geometry}${tags:+$s}${tags}${s}${filename}${s}${dstdir}"
