#!/bin/sh
bl_dev=/sys/class/backlight/intel_backlight
bl_max_val=$(< "${bl_dev}/max_brightness")
step=$(( bl_max_val / 10 ))

case $1 in
  -) echo $(($(< $bl_dev/brightness) - $step)) >$bl_dev/brightness;;
  +) echo $(($(< $bl_dev/brightness) + $step)) >$bl_dev/brightness;;
esac
